from .base import BaseConverter
from ..config import Config

class LibreOfficeConverter(BaseConverter):
    def convert(self, input_path: str, output_path: str, from_ext: str, to_ext: str) -> dict:
        if from_ext in ['.docx', '.doc', '.odt', '.rtf'] and to_ext == '.pdf':
            # LibreOffice --outdir takes a directory, not a full path
            # But wait, app.py logic was:
            # 'libreoffice', '--headless', '--convert-to', 'pdf', '--outdir', CONVERTED_FOLDER, input_path
            # The output filename is automatically generated by libreoffice based on input filename

            # However, our app expects output_path to be specific.
            # If we use --outdir, we might need to rename the file afterwards if the name changes,
            # but usually it just changes extension.

            return self.run_command([
                'libreoffice', '--headless', '--convert-to', 'pdf',
                '--outdir', Config.CONVERTED_FOLDER, input_path
            ])
        return {'success': False, 'error': 'Conversion not supported by LibreOffice'}
